import express from "express";
import home from "./home/index.js";
import contact from "./contactUs/index.js";
import service from "./services/index.js";
import facility from "./facility/index.js";
import team from "./team/index.js";
import createTable from "./createTable/index.js";
import about from "./about/index.js";
import auth from "./auth/index.js";
import donate from "./donate/index.js";
import indemnityAgreement from "./indemnityAgreement/index.js";
import parentAgreement from "./parentAgreement/index.js";
import uploadImage from "./uploadImage/index.js";
import collaborate from "./collaborate/index.js";
const router = express.Router();
router.use("/home", home);
router.use("/contact", contact);
router.use("/service", service);
router.use("/facility", facility);
router.use("/team", team);
router.use("/createTable", createTable);
router.use("/about", about);
router.use("/auth", auth);
router.use("/donate", donate);
router.use("/indemnity-agreement", indemnityAgreement);
router.use("/parent-agreement", parentAgreement);
router.use("/upload-image", uploadImage);
router.use("/collaborate", collaborate);
export default router;
